### ISSUE TITLE
how to control the actual robot 

### ISSUE THREAD

**Issue by Abduoit** [oroca/rosbook_robot_arm#1]
hi,

I run the following codes, I got rviz moveit and gazeboo. but I did not get any interactive marker in order to control the actual arm. any help please. 

```
roscore
roslaunch turtlebot_arm_bringup arm.launch 
roslaunch robot_arm_gazebo robot_arm_gazebo_world.launch 
roslaunch robot_arm_moveit_config moveit_rviz.launch
```

**Comment by robotpilot** [comment]
Hi,

Are you interested in manipulators using Dynamixel? 
This repository is not currently supported because it was created quite personally in the past.

I recommend 'OpenManipulator'. 
This manipulator supports ROS, Gazebo, and MoveIt!.
Please check the wiki below.

https://github.com/ROBOTIS-GIT/open_manipulator/wiki

Thanks,
Pyo

**Comment by Abduoit** [comment]
@robotpilot 
Thx for reply 
I want to control the actual Phantomx Pincher arm via Gazebo, rviz, Moveit, or V-REP. My final target is to make the arm tracking the object by using normal camera. 

I ll check this link, thank you

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
